apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  ELASTICSEARCH_URL: {{ (print "http://" .Release.Name "-elasticsearch-client:9200") | b64enc |quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET  | b64enc | quote }}
  AUTH0_JWT_PUTLIC_KEY: {{ .Values.secret.AUTH0_JWT_PUTLIC_KEY | quote }}
  MYSQL_DATABASE_NAME: {{ .Values.secret.MYSQL_DATABASE_NAME  | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD  | b64enc | quote }}
  MYSQL_PORT: {{ .Values.secret.MYSQL_PORT  | b64enc | quote }}
  MYSQL_SERVER: {{ .Values.secret.MYSQL_SERVER  | b64enc | quote }}
  MYSQL_USERNAME: {{ .Values.secret.MYSQL_USERNAME  | b64enc | quote }}
  RAYGUN_API_KEY: {{ .Values.secret.RAYGUN_API_KEY  | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  key.json: {{ .Values.secret.GCP_SERVICE_KEY_JSON | b64enc | quote }}
